//
//  CDTeaPlace+Extensions.swift
//  TeaTimeHarsh
//
//  Created by Harsh on 11/01/26.
//

import CoreData
import Foundation

// 🔥 Note: The CDTeaPlace class was auto-generated by Xcode.
// We are only adding additional functionality here.

extension CDTeaPlace {
    /// Converts the Managed Object (Database Entity) to App's Struct Model
    func convertToStruct() -> TeaPlace? {
        // Validation: ID and Name are mandatory
        guard let validId = id, let validName = name else { return nil }

        return TeaPlace(
            id: validId,
            name: validName,
            desc: desc,
            website: website,
            phone: phone,
            city: city,
            address: address,
            latitude: latitude,
            longitude: longitude,
            imageURL: imageURL,
            videoURL: videoURL,
            videoThumbnailURL: videoThumbnailURL,
            pdfURL: pdfURL,
            rating: rating,
            totalReviewCount: Int(totalReviewCount),
            priceRange: priceRange,
            openingTime: openingTime,
            closingTime: closingTime,
            holiday: holiday,
            createdByUserId: createdByUserId ?? "",
            createdAt: createdAt ?? Date(),
            isVisited: isVisited,
            isFav: isFav
        )
    }
}
